export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';
export const SET_SEARCH_TITLE = 'SET_SEARCH_TITLE';
export const SET_LAST_RESULTS = 'SET_LAST_RESULTS';
export const INPUT_INVALIDATE = 'INPUT_INVALIDATE';