export const GET_API_DATA = 'GET_API_DATA';
export const DATA_LOADED = 'DATA_LOADED';
export const API_ERROR = 'API_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const SET_SEARCH_TITLE = 'SET_SEARCH_TITLE';
export const SET_LAST_RESULTS = 'SET_LAST_RESULTS';
export const INPUT_INVALIDATE = 'INPUT_INVALIDATE';